### ISSUE TITLE
Check out d3 transitions to make redraw-ing the graph less aggressive 

### ISSUE THREAD

**Issue by treymo** [treymo/joplin-link-graph#16]

**Comment by laurent22** [comment]
I've noticed the plugin is posting messages every 500 ms here:

https://github.com/treymo/joplin-link-graph/blob/66e7739abeec09cde95c351ab0ad7331982988a3/src/note-graph.js#L33

As it's likely to drain people's battery rather quickly, perhaps you could look at making it update less frequently? Or even better, is it not possible to update based on an event like onNoteSelectionChange on onNoteContentChange?

**Comment by treymo** [comment]
Yeah I definitely don't want to be doing this but I didn't find a work around when developing.  Is there a way to communicate that from index.ts -> webview?  The only communication I could find was returning a response from index.ts when the webview sends a message.
