### ISSUE TITLE
Graph toggle should shrink its panel size to 0 when it is disabled

### ISSUE THREAD

**Issue by kellya** [treymo/joplin-link-graph#19]
It would be nice to have the panels redraw when the graph is toggled.  Right now it is just if the graph is displaying, but the editor panel is the same size regardless of the graph being visible or not.  It would be nice if the panel resized to 0 when the graph was disabled so the editor had more space.

I have no idea if that's even possible, and if it isn't or is a lot of work, I'd personally be just as happy with issue #12  being the way to not lose editor space when the graph is visible.

**Comment by sleekspeed22** [comment]
Definitely would love to see this.

**Comment by treymo** [comment]
Yeah, this is a strange issue and might be a Joplin bug - I still need to investigate.  When I click the graph button on my Mac, the graph area disappears completely as expected.  But I did notice the same behavior as you both on my Linux desktop.

**Comment by kellya** [comment]
I am currently sing on Fedora Linux, Gnome 3.38.4 and Joplin 1.7.11.   Today when I tried the graph, it resized as expected.  I haven't applied an update to either Joplin or the graph plugin since then.  I did update from Gnome 3.38.3 to 3.38.4 since I opened the issue, I have no idea if that is related, but at the moment have no way of testing any further since I can't reproduce the issue.

**Comment by void-m4110c** [comment]
Yep, I'm using Gentoo Linux with i3-wm and the graph window disappears completely when I press the button. So this seems to be fixed.
