### ISSUE TITLE
Toggle off graph view - return space to remaining views

### ISSUE THREAD

**Issue by sleekspeed22** [treymo/joplin-link-graph#23]
Love this... but when I toggle off the Graph view... the remaining space should be redistributed to the remaining views instead of requiring me to resize manually... like how the toggle work for markdown split window works.  Should the button resize graph to 1px width and toggle off?  I'm sure you can do something more elegant than my silly idea.

**Comment by treymo** [comment]
https://github.com/treymo/joplin-link-graph/issues/19
