### ISSUE TITLE
Keyboard shortcut to show/hide the Graph UI panel

### ISSUE THREAD

**Issue by dbogdanov** [treymo/joplin-link-graph#30]
Since the Graph UI panel occupies a lot of space, it will be useful to have a keyboard shortcut for instantaneous access to it, just like F10 and F11 toggle the notebook list and the note list.

**Comment by Ravichandra-C** [comment]
@treymo Can I work on this?

**Comment by treymo** [comment]
@Ravichandra-C Go for it!

**Comment by Ravichandra-C** [comment]
Keyboard Shortcut F8 is added. @treymo Can we close this issue?

**Comment by treymo** [comment]
Closed, thanks @Ravichandra-C !!
