### ISSUE TITLE
Graph disapperas when I try to zoom in or out on the graph

### ISSUE THREAD

**Issue by Ravichandra-C** [treymo/joplin-link-graph#37]
The Graph automatically disappears when I try to zoom in or zoom out on it.
Steps to reproduce: 
1. Launch Graph and Zoom in.

**Comment by treymo** [comment]
I don't see this behavior locally.  Do you mind sharing more details? What Joplin version? What Graph UI plugin version? What OS?   Can you record a video/gif of this happening?

**Comment by Ravichandra-C** [comment]
@treymo , 
OS: windows and 
plugin Version: 1.0.1.
Joplin: 2.3.5
I'm using the default settings for the plugin.

Initially It looks like this:

![image](https://user-images.githubusercontent.com/17808008/134857870-b40d9b9c-7bcc-455a-a2ce-1b8e695e1add.png)


When I zoom in ,it looks like this 

![image](https://user-images.githubusercontent.com/17808008/134857965-f691509c-097a-403a-bc2e-c5ef62487299.png)


Problem, I think is since we are not showing any scrollbars  user has no Idea where the Graph is on UI. He does not know if if I have to scroll up to see the graph or scroll down to see the graph.

However , If user click on "Redraw Graph " everything comes back to normal.

**Comment by Ravichandra-C** [comment]
![RollbackTest](https://user-images.githubusercontent.com/17808008/134862061-efdb542c-401c-4311-9309-f904d0e45473.gif)

**Comment by treymo** [comment]
Hey @Ravichandra-C , I made a change to the zoom functionality so you can't zoom too far away and lose track that way.   I will see if I can limit the scrolling to the edges of the graph so that people don't get lost scrolling sideways or up/down
