### ISSUE TITLE
Graph isn't drawn when max degree of separation is 0, i.e. when it should show all notes

### ISSUE THREAD

**Issue by cyphase** [treymo/joplin-link-graph#46]
When max degree of separation is 0, i.e. when the graph should show all notes, I don't see anything in the graph panel. The Redraw Graph button doesn't help. When I set a number other than 0, it works as expected, showing all notes within range that are linked downstream **from** the selected note; I believe that's the intended functionality. I'm using Joplin 2.6.2 on Linux with plugin version 1.1.3.

**Comment by cyphase** [comment]
Just tried it again on a hunch, and now it's working. Even though I tried restarting multiple times before. Not sure what changed that "fixed" it, but there's still some bug somewhere because it didn't work before. :thinking:

**Comment by treymo** [comment]
Hmmm, let me know if you figure out how to reproduce it.  I am running the plugin primarily on Linux as well. My max degree of separation has always been set to zero and I am not sure I've run into this issue.

We can reopen this issue if it pops up again
