### ISSUE TITLE
Feature request: allow hiding graph.

### ISSUE THREAD

**Issue by markusgod** [treymo/joplin-link-graph#65]
For example, add an entry to view/tools menu to hide and show graph.

**Comment by treymo** [comment]
![show-hide-graph](https://user-images.githubusercontent.com/278828/205457078-490e43e9-c1f6-4024-a872-8bf7260cb359.png)

There is a button that is added (on the right) that will show/hide the graph.  You can also use the shortcut F8.

**Comment by markusgod** [comment]
Thanks!
